<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\common.props" />

	<ItemGroup>
	  <EmbeddedResource Include="Localization\Resources\zh-Hans.json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Letu.Basis\Letu.Basis.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="PdfPig" />
		<PackageReference Include="EPPlus" />
		<PackageReference Include="DocumentFormat.OpenXml" />
		<PackageReference Include="OpenAI" />
		<PackageReference Include="SixLabors.ImageSharp" />
	</ItemGroup>

</Project>
