<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="..\common.props" />

	<PropertyGroup>
		<RootNamespace>Letu</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore" />
		<PackageReference Include="Volo.Abp.Autofac" />
		<PackageReference Include="Volo.Abp.BlobStoring.FileSystem" />
		<PackageReference Include="Volo.Abp.BackgroundWorkers.Hangfire" />
		<PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" />
		<PackageReference Include="Hangfire.PostgreSql" />
    </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Letu.Abp.FreeSql\Letu.Abp.FreeSql.csproj" />
		<ProjectReference Include="..\Letu.AI\Letu.AI.csproj" />
		<ProjectReference Include="..\Letu.Basis\Letu.Basis.csproj" />
		<ProjectReference Include="..\Letu.MobilePush.Aliyun\Letu.MobilePush.Aliyun.csproj" />
		<ProjectReference Include="..\Letu.Mqtt\Letu.Mqtt.csproj" />
	</ItemGroup>
</Project>
