/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as MyRouteRouteImport } from './pages/my/route'
import { Route as HomeRouteRouteImport } from './pages/home/route'
import { Route as AiRouteRouteImport } from './pages/ai/route'
import { Route as AdminRouteRouteImport } from './pages/admin/route'
import { Route as AccountRouteRouteImport } from './pages/account/route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as HomeIndexRouteImport } from './pages/home/index'
import { Route as MySecurityLogsRouteImport } from './pages/my/security-logs'
import { Route as MyProfileRouteImport } from './pages/my/profile'
import { Route as MyPasswordRouteImport } from './pages/my/password'
import { Route as MyActiveSessionsRouteImport } from './pages/my/active-sessions'
import { Route as AccountTenantErrorRouteImport } from './pages/account/tenant-error'
import { Route as AccountLogoutRouteImport } from './pages/account/logout'
import { Route as AccountLoginRouteImport } from './pages/account/login'
import { Route as AdminSettingsRouteRouteImport } from './pages/admin/settings/route'
import { Route as MyNotificationsIndexRouteImport } from './pages/my/notifications/index'
import { Route as AiWorkflowsIndexRouteImport } from './pages/ai/workflows/index'
import { Route as AiFileManagerIndexRouteImport } from './pages/ai/file-manager/index'
import { Route as AdminUsersIndexRouteImport } from './pages/admin/users/index'
import { Route as AdminUserDevicesIndexRouteImport } from './pages/admin/user-devices/index'
import { Route as AdminTenantsIndexRouteImport } from './pages/admin/tenants/index'
import { Route as AdminSettingsIndexRouteImport } from './pages/admin/settings/index'
import { Route as AdminRolesIndexRouteImport } from './pages/admin/roles/index'
import { Route as AdminRegionsIndexRouteImport } from './pages/admin/regions/index'
import { Route as AdminPositionsIndexRouteImport } from './pages/admin/positions/index'
import { Route as AdminOrganizationUnitsIndexRouteImport } from './pages/admin/organization-units/index'
import { Route as AdminOnlineUsersIndexRouteImport } from './pages/admin/online-users/index'
import { Route as AdminNotificationsIndexRouteImport } from './pages/admin/notifications/index'
import { Route as AdminMenusIndexRouteImport } from './pages/admin/menus/index'
import { Route as AdminIntegrationsIndexRouteImport } from './pages/admin/integrations/index'
import { Route as AdminEmployeesIndexRouteImport } from './pages/admin/employees/index'
import { Route as AdminEditionsIndexRouteImport } from './pages/admin/editions/index'
import { Route as AdminDepartmentsIndexRouteImport } from './pages/admin/departments/index'
import { Route as AdminDataDictionariesIndexRouteImport } from './pages/admin/data-dictionaries/index'
import { Route as MyNotificationsIdRouteImport } from './pages/my/notifications/$id'
import { Route as HomeDemoRegionSelectRouteImport } from './pages/home/demo/region-select'
import { Route as HomeDemoMapViewRouteImport } from './pages/home/demo/map-view'
import { Route as HomeDemoMapMarkersRouteImport } from './pages/home/demo/map-markers'
import { Route as HomeDemoMapAddressInputRouteImport } from './pages/home/demo/map-address-input'
import { Route as HomeDemoAddressPickerRouteImport } from './pages/home/demo/address-picker'
import { Route as AdminSettingsTimezoneRouteImport } from './pages/admin/settings/timezone'
import { Route as AdminSettingsSiteRouteImport } from './pages/admin/settings/site'
import { Route as AdminSettingsFeatureRouteImport } from './pages/admin/settings/feature'
import { Route as AdminSettingsEmailingRouteImport } from './pages/admin/settings/emailing'
import { Route as AdminSettingsAccountRouteImport } from './pages/admin/settings/account'
import { Route as AdminPositionsGroupsRouteImport } from './pages/admin/positions/groups'
import { Route as AdminNotificationsIdRouteImport } from './pages/admin/notifications/$id'
import { Route as AdminMenusAppNameRouteImport } from './pages/admin/menus/$appName'
import { Route as AdminLoggingsSystemRouteImport } from './pages/admin/loggings/system'
import { Route as AdminLoggingsSecurityRouteImport } from './pages/admin/loggings/security'
import { Route as AdminLoggingsBusinessRouteImport } from './pages/admin/loggings/business'
import { Route as AdminEmployeesEmployeeRouteImport } from './pages/admin/employees/employee'
import { Route as AdminDataDictionariesNameRouteImport } from './pages/admin/data-dictionaries/$name'
import { Route as AdminLoggingsAuditLogRouteRouteImport } from './pages/admin/loggings/auditLog/route'
import { Route as AiWorkflowsDesignerIndexRouteImport } from './pages/ai/workflows/designer/index'
import { Route as AdminLoggingsSystemLogViewSplatRouteImport } from './pages/admin/loggings/system-log-view.$'
import { Route as AdminLoggingsAuditLogRequestIndexRouteImport } from './pages/admin/loggings/auditLog/request/index'
import { Route as AdminLoggingsAuditLogEntityIndexRouteImport } from './pages/admin/loggings/auditLog/entity/index'
import { Route as AdminLoggingsAuditLogRequestIdRouteImport } from './pages/admin/loggings/auditLog/request/$id'
import { Route as AdminLoggingsAuditLogEntityIdRouteImport } from './pages/admin/loggings/auditLog/entity/$id'

const MyRouteRoute = MyRouteRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRouteRoute = AiRouteRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const MySecurityLogsRoute = MySecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyPasswordRoute = MyPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyActiveSessionsRoute = MyActiveSessionsRouteImport.update({
  id: '/active-sessions',
  path: '/active-sessions',
  getParentRoute: () => MyRouteRoute,
} as any)
const AccountTenantErrorRoute = AccountTenantErrorRouteImport.update({
  id: '/tenant-error',
  path: '/tenant-error',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLogoutRoute = AccountLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MyNotificationsIndexRoute = MyNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => MyRouteRoute,
} as any)
const AiWorkflowsIndexRoute = AiWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AiRouteRoute,
} as any)
const AiFileManagerIndexRoute = AiFileManagerIndexRouteImport.update({
  id: '/file-manager/',
  path: '/file-manager/',
  getParentRoute: () => AiRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserDevicesIndexRoute = AdminUserDevicesIndexRouteImport.update({
  id: '/user-devices/',
  path: '/user-devices/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegionsIndexRoute = AdminRegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPositionsIndexRoute = AdminPositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationUnitsIndexRoute =
  AdminOrganizationUnitsIndexRouteImport.update({
    id: '/organization-units/',
    path: '/organization-units/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOnlineUsersIndexRoute = AdminOnlineUsersIndexRouteImport.update({
  id: '/online-users/',
  path: '/online-users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenusIndexRoute = AdminMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntegrationsIndexRoute = AdminIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEditionsIndexRoute = AdminEditionsIndexRouteImport.update({
  id: '/editions/',
  path: '/editions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataDictionariesIndexRoute =
  AdminDataDictionariesIndexRouteImport.update({
    id: '/data-dictionaries/',
    path: '/data-dictionaries/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const MyNotificationsIdRoute = MyNotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => MyRouteRoute,
} as any)
const HomeDemoRegionSelectRoute = HomeDemoRegionSelectRouteImport.update({
  id: '/demo/region-select',
  path: '/demo/region-select',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDemoMapViewRoute = HomeDemoMapViewRouteImport.update({
  id: '/demo/map-view',
  path: '/demo/map-view',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDemoMapMarkersRoute = HomeDemoMapMarkersRouteImport.update({
  id: '/demo/map-markers',
  path: '/demo/map-markers',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDemoMapAddressInputRoute = HomeDemoMapAddressInputRouteImport.update({
  id: '/demo/map-address-input',
  path: '/demo/map-address-input',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDemoAddressPickerRoute = HomeDemoAddressPickerRouteImport.update({
  id: '/demo/address-picker',
  path: '/demo/address-picker',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AdminSettingsTimezoneRoute = AdminSettingsTimezoneRouteImport.update({
  id: '/timezone',
  path: '/timezone',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsSiteRoute = AdminSettingsSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsFeatureRoute = AdminSettingsFeatureRouteImport.update({
  id: '/feature',
  path: '/feature',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsEmailingRoute = AdminSettingsEmailingRouteImport.update({
  id: '/emailing',
  path: '/emailing',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAccountRoute = AdminSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminPositionsGroupsRoute = AdminPositionsGroupsRouteImport.update({
  id: '/positions/groups',
  path: '/positions/groups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsIdRoute = AdminNotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenusAppNameRoute = AdminMenusAppNameRouteImport.update({
  id: '/menus/$appName',
  path: '/menus/$appName',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsSystemRoute = AdminLoggingsSystemRouteImport.update({
  id: '/loggings/system',
  path: '/loggings/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsSecurityRoute = AdminLoggingsSecurityRouteImport.update({
  id: '/loggings/security',
  path: '/loggings/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsBusinessRoute = AdminLoggingsBusinessRouteImport.update({
  id: '/loggings/business',
  path: '/loggings/business',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesEmployeeRoute = AdminEmployeesEmployeeRouteImport.update({
  id: '/employees/employee',
  path: '/employees/employee',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataDictionariesNameRoute =
  AdminDataDictionariesNameRouteImport.update({
    id: '/data-dictionaries/$name',
    path: '/data-dictionaries/$name',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLoggingsAuditLogRouteRoute =
  AdminLoggingsAuditLogRouteRouteImport.update({
    id: '/loggings/auditLog',
    path: '/loggings/auditLog',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AiWorkflowsDesignerIndexRoute =
  AiWorkflowsDesignerIndexRouteImport.update({
    id: '/workflows/designer/',
    path: '/workflows/designer/',
    getParentRoute: () => AiRouteRoute,
  } as any)
const AdminLoggingsSystemLogViewSplatRoute =
  AdminLoggingsSystemLogViewSplatRouteImport.update({
    id: '/loggings/system-log-view/$',
    path: '/loggings/system-log-view/$',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLoggingsAuditLogRequestIndexRoute =
  AdminLoggingsAuditLogRequestIndexRouteImport.update({
    id: '/request/',
    path: '/request/',
    getParentRoute: () => AdminLoggingsAuditLogRouteRoute,
  } as any)
const AdminLoggingsAuditLogEntityIndexRoute =
  AdminLoggingsAuditLogEntityIndexRouteImport.update({
    id: '/entity/',
    path: '/entity/',
    getParentRoute: () => AdminLoggingsAuditLogRouteRoute,
  } as any)
const AdminLoggingsAuditLogRequestIdRoute =
  AdminLoggingsAuditLogRequestIdRouteImport.update({
    id: '/request/$id',
    path: '/request/$id',
    getParentRoute: () => AdminLoggingsAuditLogRouteRoute,
  } as any)
const AdminLoggingsAuditLogEntityIdRoute =
  AdminLoggingsAuditLogEntityIdRouteImport.update({
    id: '/entity/$id',
    path: '/entity/$id',
    getParentRoute: () => AdminLoggingsAuditLogRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/ai': typeof AiRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/account/tenant-error': typeof AccountTenantErrorRoute
  '/my/active-sessions': typeof MyActiveSessionsRoute
  '/my/password': typeof MyPasswordRoute
  '/my/profile': typeof MyProfileRoute
  '/my/security-logs': typeof MySecurityLogsRoute
  '/home/': typeof HomeIndexRoute
  '/admin/loggings/auditLog': typeof AdminLoggingsAuditLogRouteRouteWithChildren
  '/admin/data-dictionaries/$name': typeof AdminDataDictionariesNameRoute
  '/admin/employees/employee': typeof AdminEmployeesEmployeeRoute
  '/admin/loggings/business': typeof AdminLoggingsBusinessRoute
  '/admin/loggings/security': typeof AdminLoggingsSecurityRoute
  '/admin/loggings/system': typeof AdminLoggingsSystemRoute
  '/admin/menus/$appName': typeof AdminMenusAppNameRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/positions/groups': typeof AdminPositionsGroupsRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/emailing': typeof AdminSettingsEmailingRoute
  '/admin/settings/feature': typeof AdminSettingsFeatureRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/admin/settings/timezone': typeof AdminSettingsTimezoneRoute
  '/home/demo/address-picker': typeof HomeDemoAddressPickerRoute
  '/home/demo/map-address-input': typeof HomeDemoMapAddressInputRoute
  '/home/demo/map-markers': typeof HomeDemoMapMarkersRoute
  '/home/demo/map-view': typeof HomeDemoMapViewRoute
  '/home/demo/region-select': typeof HomeDemoRegionSelectRoute
  '/my/notifications/$id': typeof MyNotificationsIdRoute
  '/admin/data-dictionaries': typeof AdminDataDictionariesIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/editions': typeof AdminEditionsIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/online-users': typeof AdminOnlineUsersIndexRoute
  '/admin/organization-units': typeof AdminOrganizationUnitsIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
  '/admin/regions': typeof AdminRegionsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/admin/user-devices': typeof AdminUserDevicesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/ai/file-manager': typeof AiFileManagerIndexRoute
  '/ai/workflows': typeof AiWorkflowsIndexRoute
  '/my/notifications': typeof MyNotificationsIndexRoute
  '/admin/loggings/system-log-view/$': typeof AdminLoggingsSystemLogViewSplatRoute
  '/ai/workflows/designer': typeof AiWorkflowsDesignerIndexRoute
  '/admin/loggings/auditLog/entity/$id': typeof AdminLoggingsAuditLogEntityIdRoute
  '/admin/loggings/auditLog/request/$id': typeof AdminLoggingsAuditLogRequestIdRoute
  '/admin/loggings/auditLog/entity': typeof AdminLoggingsAuditLogEntityIndexRoute
  '/admin/loggings/auditLog/request': typeof AdminLoggingsAuditLogRequestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/ai': typeof AiRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/account/tenant-error': typeof AccountTenantErrorRoute
  '/my/active-sessions': typeof MyActiveSessionsRoute
  '/my/password': typeof MyPasswordRoute
  '/my/profile': typeof MyProfileRoute
  '/my/security-logs': typeof MySecurityLogsRoute
  '/home': typeof HomeIndexRoute
  '/admin/loggings/auditLog': typeof AdminLoggingsAuditLogRouteRouteWithChildren
  '/admin/data-dictionaries/$name': typeof AdminDataDictionariesNameRoute
  '/admin/employees/employee': typeof AdminEmployeesEmployeeRoute
  '/admin/loggings/business': typeof AdminLoggingsBusinessRoute
  '/admin/loggings/security': typeof AdminLoggingsSecurityRoute
  '/admin/loggings/system': typeof AdminLoggingsSystemRoute
  '/admin/menus/$appName': typeof AdminMenusAppNameRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/positions/groups': typeof AdminPositionsGroupsRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/emailing': typeof AdminSettingsEmailingRoute
  '/admin/settings/feature': typeof AdminSettingsFeatureRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/admin/settings/timezone': typeof AdminSettingsTimezoneRoute
  '/home/demo/address-picker': typeof HomeDemoAddressPickerRoute
  '/home/demo/map-address-input': typeof HomeDemoMapAddressInputRoute
  '/home/demo/map-markers': typeof HomeDemoMapMarkersRoute
  '/home/demo/map-view': typeof HomeDemoMapViewRoute
  '/home/demo/region-select': typeof HomeDemoRegionSelectRoute
  '/my/notifications/$id': typeof MyNotificationsIdRoute
  '/admin/data-dictionaries': typeof AdminDataDictionariesIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/editions': typeof AdminEditionsIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/online-users': typeof AdminOnlineUsersIndexRoute
  '/admin/organization-units': typeof AdminOrganizationUnitsIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
  '/admin/regions': typeof AdminRegionsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/admin/user-devices': typeof AdminUserDevicesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/ai/file-manager': typeof AiFileManagerIndexRoute
  '/ai/workflows': typeof AiWorkflowsIndexRoute
  '/my/notifications': typeof MyNotificationsIndexRoute
  '/admin/loggings/system-log-view/$': typeof AdminLoggingsSystemLogViewSplatRoute
  '/ai/workflows/designer': typeof AiWorkflowsDesignerIndexRoute
  '/admin/loggings/auditLog/entity/$id': typeof AdminLoggingsAuditLogEntityIdRoute
  '/admin/loggings/auditLog/request/$id': typeof AdminLoggingsAuditLogRequestIdRoute
  '/admin/loggings/auditLog/entity': typeof AdminLoggingsAuditLogEntityIndexRoute
  '/admin/loggings/auditLog/request': typeof AdminLoggingsAuditLogRequestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/ai': typeof AiRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/account/tenant-error': typeof AccountTenantErrorRoute
  '/my/active-sessions': typeof MyActiveSessionsRoute
  '/my/password': typeof MyPasswordRoute
  '/my/profile': typeof MyProfileRoute
  '/my/security-logs': typeof MySecurityLogsRoute
  '/home/': typeof HomeIndexRoute
  '/admin/loggings/auditLog': typeof AdminLoggingsAuditLogRouteRouteWithChildren
  '/admin/data-dictionaries/$name': typeof AdminDataDictionariesNameRoute
  '/admin/employees/employee': typeof AdminEmployeesEmployeeRoute
  '/admin/loggings/business': typeof AdminLoggingsBusinessRoute
  '/admin/loggings/security': typeof AdminLoggingsSecurityRoute
  '/admin/loggings/system': typeof AdminLoggingsSystemRoute
  '/admin/menus/$appName': typeof AdminMenusAppNameRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/positions/groups': typeof AdminPositionsGroupsRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/emailing': typeof AdminSettingsEmailingRoute
  '/admin/settings/feature': typeof AdminSettingsFeatureRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/admin/settings/timezone': typeof AdminSettingsTimezoneRoute
  '/home/demo/address-picker': typeof HomeDemoAddressPickerRoute
  '/home/demo/map-address-input': typeof HomeDemoMapAddressInputRoute
  '/home/demo/map-markers': typeof HomeDemoMapMarkersRoute
  '/home/demo/map-view': typeof HomeDemoMapViewRoute
  '/home/demo/region-select': typeof HomeDemoRegionSelectRoute
  '/my/notifications/$id': typeof MyNotificationsIdRoute
  '/admin/data-dictionaries/': typeof AdminDataDictionariesIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/editions/': typeof AdminEditionsIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/menus/': typeof AdminMenusIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/online-users/': typeof AdminOnlineUsersIndexRoute
  '/admin/organization-units/': typeof AdminOrganizationUnitsIndexRoute
  '/admin/positions/': typeof AdminPositionsIndexRoute
  '/admin/regions/': typeof AdminRegionsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/admin/user-devices/': typeof AdminUserDevicesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/ai/file-manager/': typeof AiFileManagerIndexRoute
  '/ai/workflows/': typeof AiWorkflowsIndexRoute
  '/my/notifications/': typeof MyNotificationsIndexRoute
  '/admin/loggings/system-log-view/$': typeof AdminLoggingsSystemLogViewSplatRoute
  '/ai/workflows/designer/': typeof AiWorkflowsDesignerIndexRoute
  '/admin/loggings/auditLog/entity/$id': typeof AdminLoggingsAuditLogEntityIdRoute
  '/admin/loggings/auditLog/request/$id': typeof AdminLoggingsAuditLogRequestIdRoute
  '/admin/loggings/auditLog/entity/': typeof AdminLoggingsAuditLogEntityIndexRoute
  '/admin/loggings/auditLog/request/': typeof AdminLoggingsAuditLogRequestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/home'
    | '/my'
    | '/admin/settings'
    | '/account/login'
    | '/account/logout'
    | '/account/tenant-error'
    | '/my/active-sessions'
    | '/my/password'
    | '/my/profile'
    | '/my/security-logs'
    | '/home/'
    | '/admin/loggings/auditLog'
    | '/admin/data-dictionaries/$name'
    | '/admin/employees/employee'
    | '/admin/loggings/business'
    | '/admin/loggings/security'
    | '/admin/loggings/system'
    | '/admin/menus/$appName'
    | '/admin/notifications/$id'
    | '/admin/positions/groups'
    | '/admin/settings/account'
    | '/admin/settings/emailing'
    | '/admin/settings/feature'
    | '/admin/settings/site'
    | '/admin/settings/timezone'
    | '/home/demo/address-picker'
    | '/home/demo/map-address-input'
    | '/home/demo/map-markers'
    | '/home/demo/map-view'
    | '/home/demo/region-select'
    | '/my/notifications/$id'
    | '/admin/data-dictionaries'
    | '/admin/departments'
    | '/admin/editions'
    | '/admin/employees'
    | '/admin/integrations'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/online-users'
    | '/admin/organization-units'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/roles'
    | '/admin/settings/'
    | '/admin/tenants'
    | '/admin/user-devices'
    | '/admin/users'
    | '/ai/file-manager'
    | '/ai/workflows'
    | '/my/notifications'
    | '/admin/loggings/system-log-view/$'
    | '/ai/workflows/designer'
    | '/admin/loggings/auditLog/entity/$id'
    | '/admin/loggings/auditLog/request/$id'
    | '/admin/loggings/auditLog/entity'
    | '/admin/loggings/auditLog/request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/my'
    | '/account/login'
    | '/account/logout'
    | '/account/tenant-error'
    | '/my/active-sessions'
    | '/my/password'
    | '/my/profile'
    | '/my/security-logs'
    | '/home'
    | '/admin/loggings/auditLog'
    | '/admin/data-dictionaries/$name'
    | '/admin/employees/employee'
    | '/admin/loggings/business'
    | '/admin/loggings/security'
    | '/admin/loggings/system'
    | '/admin/menus/$appName'
    | '/admin/notifications/$id'
    | '/admin/positions/groups'
    | '/admin/settings/account'
    | '/admin/settings/emailing'
    | '/admin/settings/feature'
    | '/admin/settings/site'
    | '/admin/settings/timezone'
    | '/home/demo/address-picker'
    | '/home/demo/map-address-input'
    | '/home/demo/map-markers'
    | '/home/demo/map-view'
    | '/home/demo/region-select'
    | '/my/notifications/$id'
    | '/admin/data-dictionaries'
    | '/admin/departments'
    | '/admin/editions'
    | '/admin/employees'
    | '/admin/integrations'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/online-users'
    | '/admin/organization-units'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/user-devices'
    | '/admin/users'
    | '/ai/file-manager'
    | '/ai/workflows'
    | '/my/notifications'
    | '/admin/loggings/system-log-view/$'
    | '/ai/workflows/designer'
    | '/admin/loggings/auditLog/entity/$id'
    | '/admin/loggings/auditLog/request/$id'
    | '/admin/loggings/auditLog/entity'
    | '/admin/loggings/auditLog/request'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/home'
    | '/my'
    | '/admin/settings'
    | '/account/login'
    | '/account/logout'
    | '/account/tenant-error'
    | '/my/active-sessions'
    | '/my/password'
    | '/my/profile'
    | '/my/security-logs'
    | '/home/'
    | '/admin/loggings/auditLog'
    | '/admin/data-dictionaries/$name'
    | '/admin/employees/employee'
    | '/admin/loggings/business'
    | '/admin/loggings/security'
    | '/admin/loggings/system'
    | '/admin/menus/$appName'
    | '/admin/notifications/$id'
    | '/admin/positions/groups'
    | '/admin/settings/account'
    | '/admin/settings/emailing'
    | '/admin/settings/feature'
    | '/admin/settings/site'
    | '/admin/settings/timezone'
    | '/home/demo/address-picker'
    | '/home/demo/map-address-input'
    | '/home/demo/map-markers'
    | '/home/demo/map-view'
    | '/home/demo/region-select'
    | '/my/notifications/$id'
    | '/admin/data-dictionaries/'
    | '/admin/departments/'
    | '/admin/editions/'
    | '/admin/employees/'
    | '/admin/integrations/'
    | '/admin/menus/'
    | '/admin/notifications/'
    | '/admin/online-users/'
    | '/admin/organization-units/'
    | '/admin/positions/'
    | '/admin/regions/'
    | '/admin/roles/'
    | '/admin/settings/'
    | '/admin/tenants/'
    | '/admin/user-devices/'
    | '/admin/users/'
    | '/ai/file-manager/'
    | '/ai/workflows/'
    | '/my/notifications/'
    | '/admin/loggings/system-log-view/$'
    | '/ai/workflows/designer/'
    | '/admin/loggings/auditLog/entity/$id'
    | '/admin/loggings/auditLog/request/$id'
    | '/admin/loggings/auditLog/entity/'
    | '/admin/loggings/auditLog/request/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AiRouteRoute: typeof AiRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  MyRouteRoute: typeof MyRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/my/security-logs': {
      id: '/my/security-logs'
      path: '/security-logs'
      fullPath: '/my/security-logs'
      preLoaderRoute: typeof MySecurityLogsRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/profile': {
      id: '/my/profile'
      path: '/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/password': {
      id: '/my/password'
      path: '/password'
      fullPath: '/my/password'
      preLoaderRoute: typeof MyPasswordRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/active-sessions': {
      id: '/my/active-sessions'
      path: '/active-sessions'
      fullPath: '/my/active-sessions'
      preLoaderRoute: typeof MyActiveSessionsRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/account/tenant-error': {
      id: '/account/tenant-error'
      path: '/tenant-error'
      fullPath: '/account/tenant-error'
      preLoaderRoute: typeof AccountTenantErrorRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/logout': {
      id: '/account/logout'
      path: '/logout'
      fullPath: '/account/logout'
      preLoaderRoute: typeof AccountLogoutRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/my/notifications/': {
      id: '/my/notifications/'
      path: '/notifications'
      fullPath: '/my/notifications'
      preLoaderRoute: typeof MyNotificationsIndexRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/ai/workflows/': {
      id: '/ai/workflows/'
      path: '/workflows'
      fullPath: '/ai/workflows'
      preLoaderRoute: typeof AiWorkflowsIndexRouteImport
      parentRoute: typeof AiRouteRoute
    }
    '/ai/file-manager/': {
      id: '/ai/file-manager/'
      path: '/file-manager'
      fullPath: '/ai/file-manager'
      preLoaderRoute: typeof AiFileManagerIndexRouteImport
      parentRoute: typeof AiRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user-devices/': {
      id: '/admin/user-devices/'
      path: '/user-devices'
      fullPath: '/admin/user-devices'
      preLoaderRoute: typeof AdminUserDevicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/regions/': {
      id: '/admin/regions/'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/positions/': {
      id: '/admin/positions/'
      path: '/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AdminPositionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organization-units/': {
      id: '/admin/organization-units/'
      path: '/organization-units'
      fullPath: '/admin/organization-units'
      preLoaderRoute: typeof AdminOrganizationUnitsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/online-users/': {
      id: '/admin/online-users/'
      path: '/online-users'
      fullPath: '/admin/online-users'
      preLoaderRoute: typeof AdminOnlineUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/': {
      id: '/admin/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menus/': {
      id: '/admin/menus/'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/integrations/': {
      id: '/admin/integrations/'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/editions/': {
      id: '/admin/editions/'
      path: '/editions'
      fullPath: '/admin/editions'
      preLoaderRoute: typeof AdminEditionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/departments/': {
      id: '/admin/departments/'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-dictionaries/': {
      id: '/admin/data-dictionaries/'
      path: '/data-dictionaries'
      fullPath: '/admin/data-dictionaries'
      preLoaderRoute: typeof AdminDataDictionariesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/my/notifications/$id': {
      id: '/my/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/my/notifications/$id'
      preLoaderRoute: typeof MyNotificationsIdRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/home/demo/region-select': {
      id: '/home/demo/region-select'
      path: '/demo/region-select'
      fullPath: '/home/demo/region-select'
      preLoaderRoute: typeof HomeDemoRegionSelectRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/demo/map-view': {
      id: '/home/demo/map-view'
      path: '/demo/map-view'
      fullPath: '/home/demo/map-view'
      preLoaderRoute: typeof HomeDemoMapViewRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/demo/map-markers': {
      id: '/home/demo/map-markers'
      path: '/demo/map-markers'
      fullPath: '/home/demo/map-markers'
      preLoaderRoute: typeof HomeDemoMapMarkersRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/demo/map-address-input': {
      id: '/home/demo/map-address-input'
      path: '/demo/map-address-input'
      fullPath: '/home/demo/map-address-input'
      preLoaderRoute: typeof HomeDemoMapAddressInputRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/demo/address-picker': {
      id: '/home/demo/address-picker'
      path: '/demo/address-picker'
      fullPath: '/home/demo/address-picker'
      preLoaderRoute: typeof HomeDemoAddressPickerRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/admin/settings/timezone': {
      id: '/admin/settings/timezone'
      path: '/timezone'
      fullPath: '/admin/settings/timezone'
      preLoaderRoute: typeof AdminSettingsTimezoneRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/site': {
      id: '/admin/settings/site'
      path: '/site'
      fullPath: '/admin/settings/site'
      preLoaderRoute: typeof AdminSettingsSiteRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/feature': {
      id: '/admin/settings/feature'
      path: '/feature'
      fullPath: '/admin/settings/feature'
      preLoaderRoute: typeof AdminSettingsFeatureRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/emailing': {
      id: '/admin/settings/emailing'
      path: '/emailing'
      fullPath: '/admin/settings/emailing'
      preLoaderRoute: typeof AdminSettingsEmailingRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/positions/groups': {
      id: '/admin/positions/groups'
      path: '/positions/groups'
      fullPath: '/admin/positions/groups'
      preLoaderRoute: typeof AdminPositionsGroupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/$id': {
      id: '/admin/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/admin/notifications/$id'
      preLoaderRoute: typeof AdminNotificationsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menus/$appName': {
      id: '/admin/menus/$appName'
      path: '/menus/$appName'
      fullPath: '/admin/menus/$appName'
      preLoaderRoute: typeof AdminMenusAppNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/system': {
      id: '/admin/loggings/system'
      path: '/loggings/system'
      fullPath: '/admin/loggings/system'
      preLoaderRoute: typeof AdminLoggingsSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/security': {
      id: '/admin/loggings/security'
      path: '/loggings/security'
      fullPath: '/admin/loggings/security'
      preLoaderRoute: typeof AdminLoggingsSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/business': {
      id: '/admin/loggings/business'
      path: '/loggings/business'
      fullPath: '/admin/loggings/business'
      preLoaderRoute: typeof AdminLoggingsBusinessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/employee': {
      id: '/admin/employees/employee'
      path: '/employees/employee'
      fullPath: '/admin/employees/employee'
      preLoaderRoute: typeof AdminEmployeesEmployeeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-dictionaries/$name': {
      id: '/admin/data-dictionaries/$name'
      path: '/data-dictionaries/$name'
      fullPath: '/admin/data-dictionaries/$name'
      preLoaderRoute: typeof AdminDataDictionariesNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/auditLog': {
      id: '/admin/loggings/auditLog'
      path: '/loggings/auditLog'
      fullPath: '/admin/loggings/auditLog'
      preLoaderRoute: typeof AdminLoggingsAuditLogRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/ai/workflows/designer/': {
      id: '/ai/workflows/designer/'
      path: '/workflows/designer'
      fullPath: '/ai/workflows/designer'
      preLoaderRoute: typeof AiWorkflowsDesignerIndexRouteImport
      parentRoute: typeof AiRouteRoute
    }
    '/admin/loggings/system-log-view/$': {
      id: '/admin/loggings/system-log-view/$'
      path: '/loggings/system-log-view/$'
      fullPath: '/admin/loggings/system-log-view/$'
      preLoaderRoute: typeof AdminLoggingsSystemLogViewSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/auditLog/request/': {
      id: '/admin/loggings/auditLog/request/'
      path: '/request'
      fullPath: '/admin/loggings/auditLog/request'
      preLoaderRoute: typeof AdminLoggingsAuditLogRequestIndexRouteImport
      parentRoute: typeof AdminLoggingsAuditLogRouteRoute
    }
    '/admin/loggings/auditLog/entity/': {
      id: '/admin/loggings/auditLog/entity/'
      path: '/entity'
      fullPath: '/admin/loggings/auditLog/entity'
      preLoaderRoute: typeof AdminLoggingsAuditLogEntityIndexRouteImport
      parentRoute: typeof AdminLoggingsAuditLogRouteRoute
    }
    '/admin/loggings/auditLog/request/$id': {
      id: '/admin/loggings/auditLog/request/$id'
      path: '/request/$id'
      fullPath: '/admin/loggings/auditLog/request/$id'
      preLoaderRoute: typeof AdminLoggingsAuditLogRequestIdRouteImport
      parentRoute: typeof AdminLoggingsAuditLogRouteRoute
    }
    '/admin/loggings/auditLog/entity/$id': {
      id: '/admin/loggings/auditLog/entity/$id'
      path: '/entity/$id'
      fullPath: '/admin/loggings/auditLog/entity/$id'
      preLoaderRoute: typeof AdminLoggingsAuditLogEntityIdRouteImport
      parentRoute: typeof AdminLoggingsAuditLogRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountLoginRoute: typeof AccountLoginRoute
  AccountLogoutRoute: typeof AccountLogoutRoute
  AccountTenantErrorRoute: typeof AccountTenantErrorRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountLoginRoute: AccountLoginRoute,
  AccountLogoutRoute: AccountLogoutRoute,
  AccountTenantErrorRoute: AccountTenantErrorRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsEmailingRoute: typeof AdminSettingsEmailingRoute
  AdminSettingsFeatureRoute: typeof AdminSettingsFeatureRoute
  AdminSettingsSiteRoute: typeof AdminSettingsSiteRoute
  AdminSettingsTimezoneRoute: typeof AdminSettingsTimezoneRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsEmailingRoute: AdminSettingsEmailingRoute,
  AdminSettingsFeatureRoute: AdminSettingsFeatureRoute,
  AdminSettingsSiteRoute: AdminSettingsSiteRoute,
  AdminSettingsTimezoneRoute: AdminSettingsTimezoneRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminLoggingsAuditLogRouteRouteChildren {
  AdminLoggingsAuditLogEntityIdRoute: typeof AdminLoggingsAuditLogEntityIdRoute
  AdminLoggingsAuditLogRequestIdRoute: typeof AdminLoggingsAuditLogRequestIdRoute
  AdminLoggingsAuditLogEntityIndexRoute: typeof AdminLoggingsAuditLogEntityIndexRoute
  AdminLoggingsAuditLogRequestIndexRoute: typeof AdminLoggingsAuditLogRequestIndexRoute
}

const AdminLoggingsAuditLogRouteRouteChildren: AdminLoggingsAuditLogRouteRouteChildren =
  {
    AdminLoggingsAuditLogEntityIdRoute: AdminLoggingsAuditLogEntityIdRoute,
    AdminLoggingsAuditLogRequestIdRoute: AdminLoggingsAuditLogRequestIdRoute,
    AdminLoggingsAuditLogEntityIndexRoute:
      AdminLoggingsAuditLogEntityIndexRoute,
    AdminLoggingsAuditLogRequestIndexRoute:
      AdminLoggingsAuditLogRequestIndexRoute,
  }

const AdminLoggingsAuditLogRouteRouteWithChildren =
  AdminLoggingsAuditLogRouteRoute._addFileChildren(
    AdminLoggingsAuditLogRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminLoggingsAuditLogRouteRoute: typeof AdminLoggingsAuditLogRouteRouteWithChildren
  AdminDataDictionariesNameRoute: typeof AdminDataDictionariesNameRoute
  AdminEmployeesEmployeeRoute: typeof AdminEmployeesEmployeeRoute
  AdminLoggingsBusinessRoute: typeof AdminLoggingsBusinessRoute
  AdminLoggingsSecurityRoute: typeof AdminLoggingsSecurityRoute
  AdminLoggingsSystemRoute: typeof AdminLoggingsSystemRoute
  AdminMenusAppNameRoute: typeof AdminMenusAppNameRoute
  AdminNotificationsIdRoute: typeof AdminNotificationsIdRoute
  AdminPositionsGroupsRoute: typeof AdminPositionsGroupsRoute
  AdminDataDictionariesIndexRoute: typeof AdminDataDictionariesIndexRoute
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute
  AdminEditionsIndexRoute: typeof AdminEditionsIndexRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminIntegrationsIndexRoute: typeof AdminIntegrationsIndexRoute
  AdminMenusIndexRoute: typeof AdminMenusIndexRoute
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
  AdminOnlineUsersIndexRoute: typeof AdminOnlineUsersIndexRoute
  AdminOrganizationUnitsIndexRoute: typeof AdminOrganizationUnitsIndexRoute
  AdminPositionsIndexRoute: typeof AdminPositionsIndexRoute
  AdminRegionsIndexRoute: typeof AdminRegionsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
  AdminUserDevicesIndexRoute: typeof AdminUserDevicesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminLoggingsSystemLogViewSplatRoute: typeof AdminLoggingsSystemLogViewSplatRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminLoggingsAuditLogRouteRoute: AdminLoggingsAuditLogRouteRouteWithChildren,
  AdminDataDictionariesNameRoute: AdminDataDictionariesNameRoute,
  AdminEmployeesEmployeeRoute: AdminEmployeesEmployeeRoute,
  AdminLoggingsBusinessRoute: AdminLoggingsBusinessRoute,
  AdminLoggingsSecurityRoute: AdminLoggingsSecurityRoute,
  AdminLoggingsSystemRoute: AdminLoggingsSystemRoute,
  AdminMenusAppNameRoute: AdminMenusAppNameRoute,
  AdminNotificationsIdRoute: AdminNotificationsIdRoute,
  AdminPositionsGroupsRoute: AdminPositionsGroupsRoute,
  AdminDataDictionariesIndexRoute: AdminDataDictionariesIndexRoute,
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminEditionsIndexRoute: AdminEditionsIndexRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminIntegrationsIndexRoute: AdminIntegrationsIndexRoute,
  AdminMenusIndexRoute: AdminMenusIndexRoute,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
  AdminOnlineUsersIndexRoute: AdminOnlineUsersIndexRoute,
  AdminOrganizationUnitsIndexRoute: AdminOrganizationUnitsIndexRoute,
  AdminPositionsIndexRoute: AdminPositionsIndexRoute,
  AdminRegionsIndexRoute: AdminRegionsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
  AdminUserDevicesIndexRoute: AdminUserDevicesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminLoggingsSystemLogViewSplatRoute: AdminLoggingsSystemLogViewSplatRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AiRouteRouteChildren {
  AiFileManagerIndexRoute: typeof AiFileManagerIndexRoute
  AiWorkflowsIndexRoute: typeof AiWorkflowsIndexRoute
  AiWorkflowsDesignerIndexRoute: typeof AiWorkflowsDesignerIndexRoute
}

const AiRouteRouteChildren: AiRouteRouteChildren = {
  AiFileManagerIndexRoute: AiFileManagerIndexRoute,
  AiWorkflowsIndexRoute: AiWorkflowsIndexRoute,
  AiWorkflowsDesignerIndexRoute: AiWorkflowsDesignerIndexRoute,
}

const AiRouteRouteWithChildren =
  AiRouteRoute._addFileChildren(AiRouteRouteChildren)

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeDemoAddressPickerRoute: typeof HomeDemoAddressPickerRoute
  HomeDemoMapAddressInputRoute: typeof HomeDemoMapAddressInputRoute
  HomeDemoMapMarkersRoute: typeof HomeDemoMapMarkersRoute
  HomeDemoMapViewRoute: typeof HomeDemoMapViewRoute
  HomeDemoRegionSelectRoute: typeof HomeDemoRegionSelectRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeDemoAddressPickerRoute: HomeDemoAddressPickerRoute,
  HomeDemoMapAddressInputRoute: HomeDemoMapAddressInputRoute,
  HomeDemoMapMarkersRoute: HomeDemoMapMarkersRoute,
  HomeDemoMapViewRoute: HomeDemoMapViewRoute,
  HomeDemoRegionSelectRoute: HomeDemoRegionSelectRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface MyRouteRouteChildren {
  MyActiveSessionsRoute: typeof MyActiveSessionsRoute
  MyPasswordRoute: typeof MyPasswordRoute
  MyProfileRoute: typeof MyProfileRoute
  MySecurityLogsRoute: typeof MySecurityLogsRoute
  MyNotificationsIdRoute: typeof MyNotificationsIdRoute
  MyNotificationsIndexRoute: typeof MyNotificationsIndexRoute
}

const MyRouteRouteChildren: MyRouteRouteChildren = {
  MyActiveSessionsRoute: MyActiveSessionsRoute,
  MyPasswordRoute: MyPasswordRoute,
  MyProfileRoute: MyProfileRoute,
  MySecurityLogsRoute: MySecurityLogsRoute,
  MyNotificationsIdRoute: MyNotificationsIdRoute,
  MyNotificationsIndexRoute: MyNotificationsIndexRoute,
}

const MyRouteRouteWithChildren =
  MyRouteRoute._addFileChildren(MyRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AiRouteRoute: AiRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  MyRouteRoute: MyRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
