/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as MyRouteRouteImport } from './pages/my/route'
import { Route as HomeRouteRouteImport } from './pages/home/route'
import { Route as AdminRouteRouteImport } from './pages/admin/route'
import { Route as AccountRouteRouteImport } from './pages/account/route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as HomeIndexRouteImport } from './pages/home/index'
import { Route as MySecurityLogsRouteImport } from './pages/my/security-logs'
import { Route as MyProfileRouteImport } from './pages/my/profile'
import { Route as MyPasswordRouteImport } from './pages/my/password'
import { Route as AccountTenantErrorRouteImport } from './pages/account/tenant-error'
import { Route as AccountLogoutRouteImport } from './pages/account/logout'
import { Route as AccountLoginRouteImport } from './pages/account/login'
import { Route as AdminSettingsRouteRouteImport } from './pages/admin/settings/route'
import { Route as MyNotificationsIndexRouteImport } from './pages/my/notifications/index'
import { Route as AdminUsersIndexRouteImport } from './pages/admin/users/index'
import { Route as AdminTenantsIndexRouteImport } from './pages/admin/tenants/index'
import { Route as AdminSettingsIndexRouteImport } from './pages/admin/settings/index'
import { Route as AdminScheduledTasksIndexRouteImport } from './pages/admin/scheduled-tasks/index'
import { Route as AdminRolesIndexRouteImport } from './pages/admin/roles/index'
import { Route as AdminRegionsIndexRouteImport } from './pages/admin/regions/index'
import { Route as AdminPositionsIndexRouteImport } from './pages/admin/positions/index'
import { Route as AdminOrganizationUnitsIndexRouteImport } from './pages/admin/organization-units/index'
import { Route as AdminOnlineUsersIndexRouteImport } from './pages/admin/online-users/index'
import { Route as AdminNotificationsIndexRouteImport } from './pages/admin/notifications/index'
import { Route as AdminMenusIndexRouteImport } from './pages/admin/menus/index'
import { Route as AdminEmployeesIndexRouteImport } from './pages/admin/employees/index'
import { Route as AdminEditionsIndexRouteImport } from './pages/admin/editions/index'
import { Route as AdminDepartmentsIndexRouteImport } from './pages/admin/departments/index'
import { Route as AdminDataDictionariesIndexRouteImport } from './pages/admin/data-dictionaries/index'
import { Route as MyNotificationsIdRouteImport } from './pages/my/notifications/$id'
import { Route as HomeDemoRegionRouteImport } from './pages/home/demo/region'
import { Route as AdminSettingsTimezoneRouteImport } from './pages/admin/settings/timezone'
import { Route as AdminSettingsSiteRouteImport } from './pages/admin/settings/site'
import { Route as AdminSettingsFeatureRouteImport } from './pages/admin/settings/feature'
import { Route as AdminSettingsEmailingRouteImport } from './pages/admin/settings/emailing'
import { Route as AdminSettingsAmapRouteImport } from './pages/admin/settings/amap'
import { Route as AdminSettingsAccountRouteImport } from './pages/admin/settings/account'
import { Route as AdminPositionsGroupsRouteImport } from './pages/admin/positions/groups'
import { Route as AdminNotificationsNotificationRouteImport } from './pages/admin/notifications/notification'
import { Route as AdminNotificationsIdRouteImport } from './pages/admin/notifications/$id'
import { Route as AdminMenusAppNameRouteImport } from './pages/admin/menus/$appName'
import { Route as AdminLoggingsSecurityRouteImport } from './pages/admin/loggings/security'
import { Route as AdminLoggingsExceptionRouteImport } from './pages/admin/loggings/exception'
import { Route as AdminLoggingsBusinessRouteImport } from './pages/admin/loggings/business'
import { Route as AdminLoggingsAuditlogRouteImport } from './pages/admin/loggings/auditlog'
import { Route as AdminLoggingsAccessRouteImport } from './pages/admin/loggings/access'
import { Route as AdminEmployeesEmployeeRouteImport } from './pages/admin/employees/employee'
import { Route as AdminDataDictionariesNameRouteImport } from './pages/admin/data-dictionaries/$name'
import { Route as AdminLoggingsAuditLogRequestIndexRouteImport } from './pages/admin/loggings/auditLog/request/index'
import { Route as AdminLoggingsAuditLogEntityIndexRouteImport } from './pages/admin/loggings/auditLog/entity/index'
import { Route as AdminLoggingsAuditLogRequestIdRouteImport } from './pages/admin/loggings/auditLog/request/$id'
import { Route as AdminLoggingsAuditLogEntityIdRouteImport } from './pages/admin/loggings/auditLog/entity/$id'

const MyRouteRoute = MyRouteRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const MySecurityLogsRoute = MySecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyPasswordRoute = MyPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => MyRouteRoute,
} as any)
const AccountTenantErrorRoute = AccountTenantErrorRouteImport.update({
  id: '/tenant-error',
  path: '/tenant-error',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLogoutRoute = AccountLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MyNotificationsIndexRoute = MyNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => MyRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminScheduledTasksIndexRoute =
  AdminScheduledTasksIndexRouteImport.update({
    id: '/scheduled-tasks/',
    path: '/scheduled-tasks/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegionsIndexRoute = AdminRegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPositionsIndexRoute = AdminPositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationUnitsIndexRoute =
  AdminOrganizationUnitsIndexRouteImport.update({
    id: '/organization-units/',
    path: '/organization-units/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOnlineUsersIndexRoute = AdminOnlineUsersIndexRouteImport.update({
  id: '/online-users/',
  path: '/online-users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenusIndexRoute = AdminMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEditionsIndexRoute = AdminEditionsIndexRouteImport.update({
  id: '/editions/',
  path: '/editions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataDictionariesIndexRoute =
  AdminDataDictionariesIndexRouteImport.update({
    id: '/data-dictionaries/',
    path: '/data-dictionaries/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const MyNotificationsIdRoute = MyNotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => MyRouteRoute,
} as any)
const HomeDemoRegionRoute = HomeDemoRegionRouteImport.update({
  id: '/demo/region',
  path: '/demo/region',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AdminSettingsTimezoneRoute = AdminSettingsTimezoneRouteImport.update({
  id: '/timezone',
  path: '/timezone',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsSiteRoute = AdminSettingsSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsFeatureRoute = AdminSettingsFeatureRouteImport.update({
  id: '/feature',
  path: '/feature',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsEmailingRoute = AdminSettingsEmailingRouteImport.update({
  id: '/emailing',
  path: '/emailing',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAmapRoute = AdminSettingsAmapRouteImport.update({
  id: '/amap',
  path: '/amap',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAccountRoute = AdminSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminPositionsGroupsRoute = AdminPositionsGroupsRouteImport.update({
  id: '/positions/groups',
  path: '/positions/groups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsNotificationRoute =
  AdminNotificationsNotificationRouteImport.update({
    id: '/notifications/notification',
    path: '/notifications/notification',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminNotificationsIdRoute = AdminNotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenusAppNameRoute = AdminMenusAppNameRouteImport.update({
  id: '/menus/$appName',
  path: '/menus/$appName',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsSecurityRoute = AdminLoggingsSecurityRouteImport.update({
  id: '/loggings/security',
  path: '/loggings/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsExceptionRoute = AdminLoggingsExceptionRouteImport.update({
  id: '/loggings/exception',
  path: '/loggings/exception',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsBusinessRoute = AdminLoggingsBusinessRouteImport.update({
  id: '/loggings/business',
  path: '/loggings/business',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsAuditlogRoute = AdminLoggingsAuditlogRouteImport.update({
  id: '/loggings/auditlog',
  path: '/loggings/auditlog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoggingsAccessRoute = AdminLoggingsAccessRouteImport.update({
  id: '/loggings/access',
  path: '/loggings/access',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesEmployeeRoute = AdminEmployeesEmployeeRouteImport.update({
  id: '/employees/employee',
  path: '/employees/employee',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataDictionariesNameRoute =
  AdminDataDictionariesNameRouteImport.update({
    id: '/data-dictionaries/$name',
    path: '/data-dictionaries/$name',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLoggingsAuditLogRequestIndexRoute =
  AdminLoggingsAuditLogRequestIndexRouteImport.update({
    id: '/loggings/auditLog/request/',
    path: '/loggings/auditLog/request/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLoggingsAuditLogEntityIndexRoute =
  AdminLoggingsAuditLogEntityIndexRouteImport.update({
    id: '/loggings/auditLog/entity/',
    path: '/loggings/auditLog/entity/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLoggingsAuditLogRequestIdRoute =
  AdminLoggingsAuditLogRequestIdRouteImport.update({
    id: '/loggings/auditLog/request/$id',
    path: '/loggings/auditLog/request/$id',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLoggingsAuditLogEntityIdRoute =
  AdminLoggingsAuditLogEntityIdRouteImport.update({
    id: '/loggings/auditLog/entity/$id',
    path: '/loggings/auditLog/entity/$id',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/account/tenant-error': typeof AccountTenantErrorRoute
  '/my/password': typeof MyPasswordRoute
  '/my/profile': typeof MyProfileRoute
  '/my/security-logs': typeof MySecurityLogsRoute
  '/home/': typeof HomeIndexRoute
  '/admin/data-dictionaries/$name': typeof AdminDataDictionariesNameRoute
  '/admin/employees/employee': typeof AdminEmployeesEmployeeRoute
  '/admin/loggings/access': typeof AdminLoggingsAccessRoute
  '/admin/loggings/auditlog': typeof AdminLoggingsAuditlogRoute
  '/admin/loggings/business': typeof AdminLoggingsBusinessRoute
  '/admin/loggings/exception': typeof AdminLoggingsExceptionRoute
  '/admin/loggings/security': typeof AdminLoggingsSecurityRoute
  '/admin/menus/$appName': typeof AdminMenusAppNameRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/notifications/notification': typeof AdminNotificationsNotificationRoute
  '/admin/positions/groups': typeof AdminPositionsGroupsRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/amap': typeof AdminSettingsAmapRoute
  '/admin/settings/emailing': typeof AdminSettingsEmailingRoute
  '/admin/settings/feature': typeof AdminSettingsFeatureRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/admin/settings/timezone': typeof AdminSettingsTimezoneRoute
  '/home/demo/region': typeof HomeDemoRegionRoute
  '/my/notifications/$id': typeof MyNotificationsIdRoute
  '/admin/data-dictionaries': typeof AdminDataDictionariesIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/editions': typeof AdminEditionsIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/online-users': typeof AdminOnlineUsersIndexRoute
  '/admin/organization-units': typeof AdminOrganizationUnitsIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
  '/admin/regions': typeof AdminRegionsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/scheduled-tasks': typeof AdminScheduledTasksIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/my/notifications': typeof MyNotificationsIndexRoute
  '/admin/loggings/auditLog/entity/$id': typeof AdminLoggingsAuditLogEntityIdRoute
  '/admin/loggings/auditLog/request/$id': typeof AdminLoggingsAuditLogRequestIdRoute
  '/admin/loggings/auditLog/entity': typeof AdminLoggingsAuditLogEntityIndexRoute
  '/admin/loggings/auditLog/request': typeof AdminLoggingsAuditLogRequestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/account/tenant-error': typeof AccountTenantErrorRoute
  '/my/password': typeof MyPasswordRoute
  '/my/profile': typeof MyProfileRoute
  '/my/security-logs': typeof MySecurityLogsRoute
  '/home': typeof HomeIndexRoute
  '/admin/data-dictionaries/$name': typeof AdminDataDictionariesNameRoute
  '/admin/employees/employee': typeof AdminEmployeesEmployeeRoute
  '/admin/loggings/access': typeof AdminLoggingsAccessRoute
  '/admin/loggings/auditlog': typeof AdminLoggingsAuditlogRoute
  '/admin/loggings/business': typeof AdminLoggingsBusinessRoute
  '/admin/loggings/exception': typeof AdminLoggingsExceptionRoute
  '/admin/loggings/security': typeof AdminLoggingsSecurityRoute
  '/admin/menus/$appName': typeof AdminMenusAppNameRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/notifications/notification': typeof AdminNotificationsNotificationRoute
  '/admin/positions/groups': typeof AdminPositionsGroupsRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/amap': typeof AdminSettingsAmapRoute
  '/admin/settings/emailing': typeof AdminSettingsEmailingRoute
  '/admin/settings/feature': typeof AdminSettingsFeatureRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/admin/settings/timezone': typeof AdminSettingsTimezoneRoute
  '/home/demo/region': typeof HomeDemoRegionRoute
  '/my/notifications/$id': typeof MyNotificationsIdRoute
  '/admin/data-dictionaries': typeof AdminDataDictionariesIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/editions': typeof AdminEditionsIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/online-users': typeof AdminOnlineUsersIndexRoute
  '/admin/organization-units': typeof AdminOrganizationUnitsIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
  '/admin/regions': typeof AdminRegionsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/scheduled-tasks': typeof AdminScheduledTasksIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/my/notifications': typeof MyNotificationsIndexRoute
  '/admin/loggings/auditLog/entity/$id': typeof AdminLoggingsAuditLogEntityIdRoute
  '/admin/loggings/auditLog/request/$id': typeof AdminLoggingsAuditLogRequestIdRoute
  '/admin/loggings/auditLog/entity': typeof AdminLoggingsAuditLogEntityIndexRoute
  '/admin/loggings/auditLog/request': typeof AdminLoggingsAuditLogRequestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/account/login': typeof AccountLoginRoute
  '/account/logout': typeof AccountLogoutRoute
  '/account/tenant-error': typeof AccountTenantErrorRoute
  '/my/password': typeof MyPasswordRoute
  '/my/profile': typeof MyProfileRoute
  '/my/security-logs': typeof MySecurityLogsRoute
  '/home/': typeof HomeIndexRoute
  '/admin/data-dictionaries/$name': typeof AdminDataDictionariesNameRoute
  '/admin/employees/employee': typeof AdminEmployeesEmployeeRoute
  '/admin/loggings/access': typeof AdminLoggingsAccessRoute
  '/admin/loggings/auditlog': typeof AdminLoggingsAuditlogRoute
  '/admin/loggings/business': typeof AdminLoggingsBusinessRoute
  '/admin/loggings/exception': typeof AdminLoggingsExceptionRoute
  '/admin/loggings/security': typeof AdminLoggingsSecurityRoute
  '/admin/menus/$appName': typeof AdminMenusAppNameRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/notifications/notification': typeof AdminNotificationsNotificationRoute
  '/admin/positions/groups': typeof AdminPositionsGroupsRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/amap': typeof AdminSettingsAmapRoute
  '/admin/settings/emailing': typeof AdminSettingsEmailingRoute
  '/admin/settings/feature': typeof AdminSettingsFeatureRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/admin/settings/timezone': typeof AdminSettingsTimezoneRoute
  '/home/demo/region': typeof HomeDemoRegionRoute
  '/my/notifications/$id': typeof MyNotificationsIdRoute
  '/admin/data-dictionaries/': typeof AdminDataDictionariesIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/editions/': typeof AdminEditionsIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/menus/': typeof AdminMenusIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/online-users/': typeof AdminOnlineUsersIndexRoute
  '/admin/organization-units/': typeof AdminOrganizationUnitsIndexRoute
  '/admin/positions/': typeof AdminPositionsIndexRoute
  '/admin/regions/': typeof AdminRegionsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/scheduled-tasks/': typeof AdminScheduledTasksIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/my/notifications/': typeof MyNotificationsIndexRoute
  '/admin/loggings/auditLog/entity/$id': typeof AdminLoggingsAuditLogEntityIdRoute
  '/admin/loggings/auditLog/request/$id': typeof AdminLoggingsAuditLogRequestIdRoute
  '/admin/loggings/auditLog/entity/': typeof AdminLoggingsAuditLogEntityIndexRoute
  '/admin/loggings/auditLog/request/': typeof AdminLoggingsAuditLogRequestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/home'
    | '/my'
    | '/admin/settings'
    | '/account/login'
    | '/account/logout'
    | '/account/tenant-error'
    | '/my/password'
    | '/my/profile'
    | '/my/security-logs'
    | '/home/'
    | '/admin/data-dictionaries/$name'
    | '/admin/employees/employee'
    | '/admin/loggings/access'
    | '/admin/loggings/auditlog'
    | '/admin/loggings/business'
    | '/admin/loggings/exception'
    | '/admin/loggings/security'
    | '/admin/menus/$appName'
    | '/admin/notifications/$id'
    | '/admin/notifications/notification'
    | '/admin/positions/groups'
    | '/admin/settings/account'
    | '/admin/settings/amap'
    | '/admin/settings/emailing'
    | '/admin/settings/feature'
    | '/admin/settings/site'
    | '/admin/settings/timezone'
    | '/home/demo/region'
    | '/my/notifications/$id'
    | '/admin/data-dictionaries'
    | '/admin/departments'
    | '/admin/editions'
    | '/admin/employees'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/online-users'
    | '/admin/organization-units'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/roles'
    | '/admin/scheduled-tasks'
    | '/admin/settings/'
    | '/admin/tenants'
    | '/admin/users'
    | '/my/notifications'
    | '/admin/loggings/auditLog/entity/$id'
    | '/admin/loggings/auditLog/request/$id'
    | '/admin/loggings/auditLog/entity'
    | '/admin/loggings/auditLog/request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/my'
    | '/account/login'
    | '/account/logout'
    | '/account/tenant-error'
    | '/my/password'
    | '/my/profile'
    | '/my/security-logs'
    | '/home'
    | '/admin/data-dictionaries/$name'
    | '/admin/employees/employee'
    | '/admin/loggings/access'
    | '/admin/loggings/auditlog'
    | '/admin/loggings/business'
    | '/admin/loggings/exception'
    | '/admin/loggings/security'
    | '/admin/menus/$appName'
    | '/admin/notifications/$id'
    | '/admin/notifications/notification'
    | '/admin/positions/groups'
    | '/admin/settings/account'
    | '/admin/settings/amap'
    | '/admin/settings/emailing'
    | '/admin/settings/feature'
    | '/admin/settings/site'
    | '/admin/settings/timezone'
    | '/home/demo/region'
    | '/my/notifications/$id'
    | '/admin/data-dictionaries'
    | '/admin/departments'
    | '/admin/editions'
    | '/admin/employees'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/online-users'
    | '/admin/organization-units'
    | '/admin/positions'
    | '/admin/regions'
    | '/admin/roles'
    | '/admin/scheduled-tasks'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/my/notifications'
    | '/admin/loggings/auditLog/entity/$id'
    | '/admin/loggings/auditLog/request/$id'
    | '/admin/loggings/auditLog/entity'
    | '/admin/loggings/auditLog/request'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/home'
    | '/my'
    | '/admin/settings'
    | '/account/login'
    | '/account/logout'
    | '/account/tenant-error'
    | '/my/password'
    | '/my/profile'
    | '/my/security-logs'
    | '/home/'
    | '/admin/data-dictionaries/$name'
    | '/admin/employees/employee'
    | '/admin/loggings/access'
    | '/admin/loggings/auditlog'
    | '/admin/loggings/business'
    | '/admin/loggings/exception'
    | '/admin/loggings/security'
    | '/admin/menus/$appName'
    | '/admin/notifications/$id'
    | '/admin/notifications/notification'
    | '/admin/positions/groups'
    | '/admin/settings/account'
    | '/admin/settings/amap'
    | '/admin/settings/emailing'
    | '/admin/settings/feature'
    | '/admin/settings/site'
    | '/admin/settings/timezone'
    | '/home/demo/region'
    | '/my/notifications/$id'
    | '/admin/data-dictionaries/'
    | '/admin/departments/'
    | '/admin/editions/'
    | '/admin/employees/'
    | '/admin/menus/'
    | '/admin/notifications/'
    | '/admin/online-users/'
    | '/admin/organization-units/'
    | '/admin/positions/'
    | '/admin/regions/'
    | '/admin/roles/'
    | '/admin/scheduled-tasks/'
    | '/admin/settings/'
    | '/admin/tenants/'
    | '/admin/users/'
    | '/my/notifications/'
    | '/admin/loggings/auditLog/entity/$id'
    | '/admin/loggings/auditLog/request/$id'
    | '/admin/loggings/auditLog/entity/'
    | '/admin/loggings/auditLog/request/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  MyRouteRoute: typeof MyRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/my/security-logs': {
      id: '/my/security-logs'
      path: '/security-logs'
      fullPath: '/my/security-logs'
      preLoaderRoute: typeof MySecurityLogsRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/profile': {
      id: '/my/profile'
      path: '/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/password': {
      id: '/my/password'
      path: '/password'
      fullPath: '/my/password'
      preLoaderRoute: typeof MyPasswordRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/account/tenant-error': {
      id: '/account/tenant-error'
      path: '/tenant-error'
      fullPath: '/account/tenant-error'
      preLoaderRoute: typeof AccountTenantErrorRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/logout': {
      id: '/account/logout'
      path: '/logout'
      fullPath: '/account/logout'
      preLoaderRoute: typeof AccountLogoutRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/my/notifications/': {
      id: '/my/notifications/'
      path: '/notifications'
      fullPath: '/my/notifications'
      preLoaderRoute: typeof MyNotificationsIndexRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/scheduled-tasks/': {
      id: '/admin/scheduled-tasks/'
      path: '/scheduled-tasks'
      fullPath: '/admin/scheduled-tasks'
      preLoaderRoute: typeof AdminScheduledTasksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/regions/': {
      id: '/admin/regions/'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/positions/': {
      id: '/admin/positions/'
      path: '/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AdminPositionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organization-units/': {
      id: '/admin/organization-units/'
      path: '/organization-units'
      fullPath: '/admin/organization-units'
      preLoaderRoute: typeof AdminOrganizationUnitsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/online-users/': {
      id: '/admin/online-users/'
      path: '/online-users'
      fullPath: '/admin/online-users'
      preLoaderRoute: typeof AdminOnlineUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/': {
      id: '/admin/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menus/': {
      id: '/admin/menus/'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/editions/': {
      id: '/admin/editions/'
      path: '/editions'
      fullPath: '/admin/editions'
      preLoaderRoute: typeof AdminEditionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/departments/': {
      id: '/admin/departments/'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-dictionaries/': {
      id: '/admin/data-dictionaries/'
      path: '/data-dictionaries'
      fullPath: '/admin/data-dictionaries'
      preLoaderRoute: typeof AdminDataDictionariesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/my/notifications/$id': {
      id: '/my/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/my/notifications/$id'
      preLoaderRoute: typeof MyNotificationsIdRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/home/demo/region': {
      id: '/home/demo/region'
      path: '/demo/region'
      fullPath: '/home/demo/region'
      preLoaderRoute: typeof HomeDemoRegionRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/admin/settings/timezone': {
      id: '/admin/settings/timezone'
      path: '/timezone'
      fullPath: '/admin/settings/timezone'
      preLoaderRoute: typeof AdminSettingsTimezoneRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/site': {
      id: '/admin/settings/site'
      path: '/site'
      fullPath: '/admin/settings/site'
      preLoaderRoute: typeof AdminSettingsSiteRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/feature': {
      id: '/admin/settings/feature'
      path: '/feature'
      fullPath: '/admin/settings/feature'
      preLoaderRoute: typeof AdminSettingsFeatureRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/emailing': {
      id: '/admin/settings/emailing'
      path: '/emailing'
      fullPath: '/admin/settings/emailing'
      preLoaderRoute: typeof AdminSettingsEmailingRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/amap': {
      id: '/admin/settings/amap'
      path: '/amap'
      fullPath: '/admin/settings/amap'
      preLoaderRoute: typeof AdminSettingsAmapRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/positions/groups': {
      id: '/admin/positions/groups'
      path: '/positions/groups'
      fullPath: '/admin/positions/groups'
      preLoaderRoute: typeof AdminPositionsGroupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/notification': {
      id: '/admin/notifications/notification'
      path: '/notifications/notification'
      fullPath: '/admin/notifications/notification'
      preLoaderRoute: typeof AdminNotificationsNotificationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/$id': {
      id: '/admin/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/admin/notifications/$id'
      preLoaderRoute: typeof AdminNotificationsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menus/$appName': {
      id: '/admin/menus/$appName'
      path: '/menus/$appName'
      fullPath: '/admin/menus/$appName'
      preLoaderRoute: typeof AdminMenusAppNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/security': {
      id: '/admin/loggings/security'
      path: '/loggings/security'
      fullPath: '/admin/loggings/security'
      preLoaderRoute: typeof AdminLoggingsSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/exception': {
      id: '/admin/loggings/exception'
      path: '/loggings/exception'
      fullPath: '/admin/loggings/exception'
      preLoaderRoute: typeof AdminLoggingsExceptionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/business': {
      id: '/admin/loggings/business'
      path: '/loggings/business'
      fullPath: '/admin/loggings/business'
      preLoaderRoute: typeof AdminLoggingsBusinessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/auditlog': {
      id: '/admin/loggings/auditlog'
      path: '/loggings/auditlog'
      fullPath: '/admin/loggings/auditlog'
      preLoaderRoute: typeof AdminLoggingsAuditlogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/access': {
      id: '/admin/loggings/access'
      path: '/loggings/access'
      fullPath: '/admin/loggings/access'
      preLoaderRoute: typeof AdminLoggingsAccessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/employee': {
      id: '/admin/employees/employee'
      path: '/employees/employee'
      fullPath: '/admin/employees/employee'
      preLoaderRoute: typeof AdminEmployeesEmployeeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-dictionaries/$name': {
      id: '/admin/data-dictionaries/$name'
      path: '/data-dictionaries/$name'
      fullPath: '/admin/data-dictionaries/$name'
      preLoaderRoute: typeof AdminDataDictionariesNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/auditLog/request/': {
      id: '/admin/loggings/auditLog/request/'
      path: '/loggings/auditLog/request'
      fullPath: '/admin/loggings/auditLog/request'
      preLoaderRoute: typeof AdminLoggingsAuditLogRequestIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/auditLog/entity/': {
      id: '/admin/loggings/auditLog/entity/'
      path: '/loggings/auditLog/entity'
      fullPath: '/admin/loggings/auditLog/entity'
      preLoaderRoute: typeof AdminLoggingsAuditLogEntityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/auditLog/request/$id': {
      id: '/admin/loggings/auditLog/request/$id'
      path: '/loggings/auditLog/request/$id'
      fullPath: '/admin/loggings/auditLog/request/$id'
      preLoaderRoute: typeof AdminLoggingsAuditLogRequestIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/loggings/auditLog/entity/$id': {
      id: '/admin/loggings/auditLog/entity/$id'
      path: '/loggings/auditLog/entity/$id'
      fullPath: '/admin/loggings/auditLog/entity/$id'
      preLoaderRoute: typeof AdminLoggingsAuditLogEntityIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountLoginRoute: typeof AccountLoginRoute
  AccountLogoutRoute: typeof AccountLogoutRoute
  AccountTenantErrorRoute: typeof AccountTenantErrorRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountLoginRoute: AccountLoginRoute,
  AccountLogoutRoute: AccountLogoutRoute,
  AccountTenantErrorRoute: AccountTenantErrorRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsAmapRoute: typeof AdminSettingsAmapRoute
  AdminSettingsEmailingRoute: typeof AdminSettingsEmailingRoute
  AdminSettingsFeatureRoute: typeof AdminSettingsFeatureRoute
  AdminSettingsSiteRoute: typeof AdminSettingsSiteRoute
  AdminSettingsTimezoneRoute: typeof AdminSettingsTimezoneRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsAmapRoute: AdminSettingsAmapRoute,
  AdminSettingsEmailingRoute: AdminSettingsEmailingRoute,
  AdminSettingsFeatureRoute: AdminSettingsFeatureRoute,
  AdminSettingsSiteRoute: AdminSettingsSiteRoute,
  AdminSettingsTimezoneRoute: AdminSettingsTimezoneRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminDataDictionariesNameRoute: typeof AdminDataDictionariesNameRoute
  AdminEmployeesEmployeeRoute: typeof AdminEmployeesEmployeeRoute
  AdminLoggingsAccessRoute: typeof AdminLoggingsAccessRoute
  AdminLoggingsAuditlogRoute: typeof AdminLoggingsAuditlogRoute
  AdminLoggingsBusinessRoute: typeof AdminLoggingsBusinessRoute
  AdminLoggingsExceptionRoute: typeof AdminLoggingsExceptionRoute
  AdminLoggingsSecurityRoute: typeof AdminLoggingsSecurityRoute
  AdminMenusAppNameRoute: typeof AdminMenusAppNameRoute
  AdminNotificationsIdRoute: typeof AdminNotificationsIdRoute
  AdminNotificationsNotificationRoute: typeof AdminNotificationsNotificationRoute
  AdminPositionsGroupsRoute: typeof AdminPositionsGroupsRoute
  AdminDataDictionariesIndexRoute: typeof AdminDataDictionariesIndexRoute
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute
  AdminEditionsIndexRoute: typeof AdminEditionsIndexRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminMenusIndexRoute: typeof AdminMenusIndexRoute
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
  AdminOnlineUsersIndexRoute: typeof AdminOnlineUsersIndexRoute
  AdminOrganizationUnitsIndexRoute: typeof AdminOrganizationUnitsIndexRoute
  AdminPositionsIndexRoute: typeof AdminPositionsIndexRoute
  AdminRegionsIndexRoute: typeof AdminRegionsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminScheduledTasksIndexRoute: typeof AdminScheduledTasksIndexRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminLoggingsAuditLogEntityIdRoute: typeof AdminLoggingsAuditLogEntityIdRoute
  AdminLoggingsAuditLogRequestIdRoute: typeof AdminLoggingsAuditLogRequestIdRoute
  AdminLoggingsAuditLogEntityIndexRoute: typeof AdminLoggingsAuditLogEntityIndexRoute
  AdminLoggingsAuditLogRequestIndexRoute: typeof AdminLoggingsAuditLogRequestIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminDataDictionariesNameRoute: AdminDataDictionariesNameRoute,
  AdminEmployeesEmployeeRoute: AdminEmployeesEmployeeRoute,
  AdminLoggingsAccessRoute: AdminLoggingsAccessRoute,
  AdminLoggingsAuditlogRoute: AdminLoggingsAuditlogRoute,
  AdminLoggingsBusinessRoute: AdminLoggingsBusinessRoute,
  AdminLoggingsExceptionRoute: AdminLoggingsExceptionRoute,
  AdminLoggingsSecurityRoute: AdminLoggingsSecurityRoute,
  AdminMenusAppNameRoute: AdminMenusAppNameRoute,
  AdminNotificationsIdRoute: AdminNotificationsIdRoute,
  AdminNotificationsNotificationRoute: AdminNotificationsNotificationRoute,
  AdminPositionsGroupsRoute: AdminPositionsGroupsRoute,
  AdminDataDictionariesIndexRoute: AdminDataDictionariesIndexRoute,
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminEditionsIndexRoute: AdminEditionsIndexRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminMenusIndexRoute: AdminMenusIndexRoute,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
  AdminOnlineUsersIndexRoute: AdminOnlineUsersIndexRoute,
  AdminOrganizationUnitsIndexRoute: AdminOrganizationUnitsIndexRoute,
  AdminPositionsIndexRoute: AdminPositionsIndexRoute,
  AdminRegionsIndexRoute: AdminRegionsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminScheduledTasksIndexRoute: AdminScheduledTasksIndexRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminLoggingsAuditLogEntityIdRoute: AdminLoggingsAuditLogEntityIdRoute,
  AdminLoggingsAuditLogRequestIdRoute: AdminLoggingsAuditLogRequestIdRoute,
  AdminLoggingsAuditLogEntityIndexRoute: AdminLoggingsAuditLogEntityIndexRoute,
  AdminLoggingsAuditLogRequestIndexRoute:
    AdminLoggingsAuditLogRequestIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeDemoRegionRoute: typeof HomeDemoRegionRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeDemoRegionRoute: HomeDemoRegionRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface MyRouteRouteChildren {
  MyPasswordRoute: typeof MyPasswordRoute
  MyProfileRoute: typeof MyProfileRoute
  MySecurityLogsRoute: typeof MySecurityLogsRoute
  MyNotificationsIdRoute: typeof MyNotificationsIdRoute
  MyNotificationsIndexRoute: typeof MyNotificationsIndexRoute
}

const MyRouteRouteChildren: MyRouteRouteChildren = {
  MyPasswordRoute: MyPasswordRoute,
  MyProfileRoute: MyProfileRoute,
  MySecurityLogsRoute: MySecurityLogsRoute,
  MyNotificationsIdRoute: MyNotificationsIdRoute,
  MyNotificationsIndexRoute: MyNotificationsIndexRoute,
}

const MyRouteRouteWithChildren =
  MyRouteRoute._addFileChildren(MyRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  MyRouteRoute: MyRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
